Update adafruit_espatcontrol_socket.py
I got error when using adafruit_espatcontrol_socket.py and  adafruit_minimqtt  when I use port 1883 for MQTT, it is due to connection type is not defined for port 1883

Traceback (most recent call last):
  File "code.py", line 117, in <module>
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 447, in connect
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 270, in _get_connect_socket
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol_socket.py", line 85, in connect
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol.py", line 202, in socket_connect
RuntimeError: Connection type must be TCP, UDL or SSL

I propose to add conntype TCP for port 1883